const fs = require('fs');
const path = require('path');

/**
 * Extracts test metrics from the Mochawesome output and writes
 * cypress/reports/test-metrics.json (consumed by the CI summary and
 * PR comment steps) plus an append-only CSV for trend analysis.
 *
 * Sources, in order of preference:
 *   1. Mochawesome JSON files generated by cypress-mochawesome-reporter
 *   2. Stats embedded in the HTML report (fallback)
 *
 * Exits 1 if there are failed tests or no report is found, so it can
 * gate a CI job.
 */
function extractMetrics() {
  try {
    const jsonCandidates = [
      path.join(__dirname, '../cypress/reports/html/index.json'),
      path.join(__dirname, '../cypress/reports/merged-report.json'),
      path.join(__dirname, '../cypress/reports/html/.jsons/mochawesome.json'),
      path.join(__dirname, '../cypress/reports/json/.jsons/mochawesome.json'),
      path.join(__dirname, '../cypress/reports/json/mochawesome.json'),
      path.join(__dirname, '../cypress/reports/html/mochawesome.json')
    ];

    for (const jsonPath of jsonCandidates) {
      if (fs.existsSync(jsonPath)) {
        console.log(`📄 Extracting metrics from JSON: ${jsonPath}`);
        const report = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
        if (report.stats) {
          generateMetricsFromStats(report.stats);
          return;
        }
      }
    }

    // Fallback: parse the stats object embedded in the HTML report
    const htmlReportPath = path.join(__dirname, '../cypress/reports/html/index.html');
    if (fs.existsSync(htmlReportPath)) {
      console.log(`📄 Extracting metrics from HTML: ${htmlReportPath}`);
      const htmlContent = fs.readFileSync(htmlReportPath, 'utf8');

      // The report embeds its data as HTML-entity-escaped JSON in the
      // <body data-raw="..."> attribute; unescape it before parsing.
      const rawMatch = htmlContent.match(/data-raw="([^"]+)"/);
      if (rawMatch) {
        try {
          const unescaped = rawMatch[1]
            .replace(/&quot;/g, '"')
            .replace(/&#39;/g, "'")
            .replace(/&lt;/g, '<')
            .replace(/&gt;/g, '>')
            .replace(/&amp;/g, '&');
          const report = JSON.parse(unescaped);
          if (report.stats) {
            generateMetricsFromStats(report.stats);
            return;
          }
        } catch (parseError) {
          console.log('⚠️ Could not parse stats JSON embedded in HTML');
        }
      }
    }

    console.error('❌ No Mochawesome report found (JSON or HTML)');
    process.exit(1);
  } catch (error) {
    console.error('❌ Error extracting metrics:', error.message);
    process.exit(1);
  }
}

function generateMetricsFromStats(stats) {
  const metrics = {
    timestamp: new Date().toISOString(),
    totalTests: stats.tests || 0,
    totalPasses: stats.passes || 0,
    totalFailures: stats.failures || 0,
    totalPending: stats.pending || 0,
    totalSkipped: stats.skipped || 0,
    duration: stats.duration || 0,
    durationInSeconds: Math.round((stats.duration || 0) / 1000),
    passRate: stats.tests > 0 ? ((stats.passes / stats.tests) * 100).toFixed(2) + '%' : '0%',
    failRate: stats.tests > 0 ? ((stats.failures / stats.tests) * 100).toFixed(2) + '%' : '0%',
    status: (stats.failures || 0) === 0 ? 'PASSED' : 'FAILED'
  };

  console.log('\n📊 TEST METRICS SUMMARY');
  console.log('========================');
  console.log(`Total Tests: ${metrics.totalTests}`);
  console.log(`✅ Passed: ${metrics.totalPasses}`);
  console.log(`❌ Failed: ${metrics.totalFailures}`);
  console.log(`⏳ Pending: ${metrics.totalPending}`);
  console.log(`⏭️  Skipped: ${metrics.totalSkipped}`);
  console.log(`🕐 Duration: ${metrics.durationInSeconds}s`);
  console.log(`📈 Pass Rate: ${metrics.passRate}`);
  console.log(`📉 Fail Rate: ${metrics.failRate}`);
  console.log(`🏆 Status: ${metrics.status}`);
  console.log('========================\n');

  const reportsDir = path.join(__dirname, '../cypress/reports');
  fs.mkdirSync(reportsDir, { recursive: true });

  const metricsPath = path.join(reportsDir, 'test-metrics.json');
  fs.writeFileSync(metricsPath, JSON.stringify(metrics, null, 2));
  console.log(`💾 Metrics saved to: ${metricsPath}`);

  const csvPath = path.join(reportsDir, 'test-metrics.csv');
  const csvHeader = 'timestamp,totalTests,totalPasses,totalFailures,totalPending,totalSkipped,duration,passRate,status\n';
  const csvRow = `${metrics.timestamp},${metrics.totalTests},${metrics.totalPasses},${metrics.totalFailures},${metrics.totalPending},${metrics.totalSkipped},${metrics.duration},${metrics.passRate},${metrics.status}\n`;

  if (!fs.existsSync(csvPath)) {
    fs.writeFileSync(csvPath, csvHeader + csvRow);
  } else {
    fs.appendFileSync(csvPath, csvRow);
  }
  console.log(`📈 CSV metrics updated at: ${csvPath}`);

  process.exit(metrics.totalFailures > 0 ? 1 : 0);
}

if (require.main === module) {
  extractMetrics();
}

module.exports = { extractMetrics };
